apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommender-hpa
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-recommender
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: faulty_cpu
      target:
        type: Value
        value: 200